
env = Environment()

if env['CC'] == 'gcc':
    env.Append(CXXFLAGS=['-std=gnu++20', '-O2'])


if env['CC'] == 'cl':
    env.Append(CXXFLAGS=['/wd4503', '/wd4530', '/std:c++20'])
    env.Append(CPPDEFINES=['_VARIADIC_MAX=15'])
    #env.Append(LINKFLAGS=['/DEBUG:FULL'])


if env['PLATFORM'] == 'win32' and (env.Detect('mingw32-gcc') or env.Detect('gcc')):
    env.Append(CPPDEFINES={'GTEST_OS_WINDOWS': '1', 'GTEST_HAS_PTHREAD': '0',
               'EMULATE_GLIBC': '1', '_EMULATE_GLIBC': '1'})


env.Append(CPPPATH = ['#/./', '#inc', ])
sources = env.Object(env.Glob('#/src/*.cpp'))
library = env.StaticLibrary('blitz_query_cpp', sources)
env.Alias("buid", [library])
